var h5w_lang_pl = {
	"home" : "Home",
	"insert" : "Wstaw",
	"htmlelements" : "Elementy HTML",
	"undo" : "Cofnij",
	"redo" : "Ponów",
	"selectall" : "Zaznacz wszystko",
	"paste" : "Wklej",
	"cut" : "Wytnij",
	"copy" : "Kopiuj",
	"fonttype" : "Typ czcionki",
	"fonttypepicker" : "Wybierz typ czcionki",
	"fontsize" : "Rozmiar czcionki",
	"fontsizepicker" : "Wybierz rozmiar czcionki",
	"bold" : "Pogrubienie",
	"italic" : "Kursywa",
	"underline" : "Podkreślenie",
	"strike" : "Przekreślenie",
	"subscript" : "Dolny indeks",
	"superscript" : "Górny indeks",
	"setfontcolor" : "Ustaw kolor czcionki",
	"fontcolorpicker" : "Wybierz kolor czcionki",
	"highlight" : "Zaznaczenie",
	"highlightcolorpicker" : "Wybierz kolor zaznaczenia",
	"removeformat" : "Usuń formatowanie",
	"addrule" : "Dodaj linie",
	"addlistnumeric" : "Dodaj listę numeryczną",
	"addlistbull" : "Dodaj listę wykropkowaną",
	"leftjustify" : "Formatowanie do lewej",
	"centerjustify" : "Wyśrodkowanie",
	"rightjustify" : "Formatowanie do prawej",
	"ident" : "Wcięcie",
	"outdent" : "Usuń wcięcie",
	"paragraph" : "Nowy paragraf",
	"attributes" : "Atrybuty",
	"delete" : "Usuń",
	"elementoptions" : "Opcje elementu",
	"quit" : "Wyjście",
	"sourcehtml" : "Edytor HTML",
	"visual" : "Edytor wizualny",
	"inserthtmlform" : "Wstaw formularz HTML",
	"image" : "Obrazek",
	"link" : "Link",
	"unlink" : "Usuń Link",
	"table" : "Tabela",
	"insetfieldset" : "Dodaj element fieldset",
	"insertinputtext" : "Wstaw pole tekstowe",
	"insertinputpassword" : "Wstaw pole na hasło",
	"insertinputcheckbox" : "Dodaj checkbox",
	"insertinputradio" : "Dodaj input radio",
	"insertinputsubmit" : "Dodaj submit",
	"insertinputbutton" : "Dodaj przycisk",
	"inserttextarea" : "Dodaj textarea"
};