var h5w_lang_ru = {
	"home" : "Главная", 
	"insert" : "Вставить", 
	"htmlelements" :"HTML элементы", 
	"undo" : "Отменить", 
	"redo" : "Повторить", 
	"selectall" : "Выбрать всё", 
	"paste" : "Вставить", 
	"cut" : "Вырезать", 
	"copy" : "Копировать" , 
	"fonttype" : "Тип шрифта", 
	"fonttypepicker" : "Выбрать тип шрифта" , 
	"fontsize" : "Размер шрифта" , 
	"fontsizepicker" : "Выбрать размер шрифта", 
	"bold" : "Жирный", 
	"italic" : "Курсив" , 
	"underline" : "Подчеркнутый", 
	"strike" : "Зачеркнутый" , 
	"subscript" : "Подстрочный", 
	"superscript" : "Надстрочный", 
	"setfontcolor" : "Цвет шрифта" , 
	"fontcolorpicker" : "Выбрать цвет шрифта", 
	"highlight" : "Выделить цветом", 
	"highlightcolorpicker" : "Выбрать цвет выделения", 
	"removeformat" : "Очистить форматирование", 
	"addrule" : "Добавить линию", 
	"addlistnumeric" : "Вставить нумерованный список", 
	"addlistbull" : "Вытавить маркированный список", 
	"leftjustify" : "Выровнять по левому краю", 
	"centerjustify" : "Выровнять по центру", 
	"rightjustify" : "Выровнять по правому краю", 
	"ident" : "Отступ" , 
	"outdent" : "Удалить отступ", 
	"paragraph" : "Новый параграф", 
	"attributes" : "Атрибуты", 
	"delete" : "Удалить", 
	"elementoptions" : "Параметры элемента", 
	"quit" : "Выход", 
	"sourcehtml" : "Редактировать HTML", 
	"visual" : "Визуальный редактор", 
	"inserthtmlform" : "Вставить HTML форму", 
	"image" : "Рисунок", 
	"link" : "Ссылка" , 
	"unlink" : "Удалить ссылку", 
	"table" : "Таблица", 
	"insetfieldset" : "Добавить элемент fieldset", 
	"insertinputtext" : "Добавить текстовое поле", 
	"insertinputpassword" : "Добавить поле для ввода пароля", 
	"insertinputcheckbox" : "Добавить переключатель checkbox", 
	"insertinputradio" : "Добавить переключатель radio", 
	"insertinputsubmit" : "Добавить кнопку отправки формы", 
	"insertinputbutton" : "Добавить кнопку", 
	"inserttextarea" : "Добавить многострочное текстовое поле", 
};
