var h5w_lang_pl = {
	"home" : "Home",
	"insert" : "Insert",
	"htmlelements" : "HTML Elements",
	"undo" : "Undo",
	"redo" : "Redo",
	"selectall" : "Select all",
	"paste" : "Paste",
	"cut" : "Cut",
	"copy" : "Copy",
	"fonttype" : "Font type",
	"fonttypepicker" : "Select font type",
	"fontsize" : "Font size",
	"fontsizepicker" : "Select font size",
	"bold" : "Bold",
	"italic" : "Italic",
	"underline" : "Underline",
	"strike" : "Strike",
	"subscript" : "Subscript",
	"superscript" : "Superscript",
	"setfontcolor" : "Set font color",
	"fontcolorpicker" : "Select font color",
	"highlight" : "Highlight",
	"highlightcolorpicker" : "Select highlight color",
	"removeformat" : "Delete formating",
	"addrule" : "Add rule",
	"addlistnumeric" : "Add numeric list",
	"addlistbull" : "Add bull list",
	"leftjustify" : "Left justify",
	"centerjustify" : "Center justify",
	"rightjustify" : "Right justify",
	"ident" : "Ident",
	"outdent" : "Outdent",
	"paragraph" : "New paragraph",
	"attributes" : "Attributes",
	"delete" : "Delete",
	"elementoptions" : "Element options",
	"quit" : "Quit",
	"sourcehtml" : "Source HTML",
	"visual" : "Visual",
	"inserthtmlform" : "Insert HTML form",
	"image" : "Image",
	"link" : "Link",
	"unlink" : "Unlink",
	"table" : "Tabele",
	"insetfieldset" : "Insert fieldset",
	"insertinputtext" : "Insert text field",
	"insertinputpassword" : "Insert password filed",
	"insertinputcheckbox" : "Insert checkbox",
	"insertinputradio" : "Insert input radio",
	"insertinputsubmit" : "Insert submit",
	"insertinputbutton" : "Insert button",
	"inserttextarea" : "Insert textarea"
};