var h5w_lang_ru = {
	"home" : "главная", 
	"insert" : "вставить", 
	"htmlelements" :"элементы HTML", 
	"undo" : "назад", 
	"redo" : "опять", 
	"selectall" : "Выбрать всё", 
	"paste" : "вставлять", 
	"cut" : "вырезать", 
	"copy" : "копируйте" , 
	"fonttype" : "тип шрифта", 
	"fonttypepicker" : "Выберите тип шрифта" , 
	"fontsize" : "Размер шрифта" , 
	"fontsizepicker" : "Выберите размер шрифта", 
	"bold" : "утолщение", 
	"italic" : "курсив" , 
	"underline" : "подчеркивание", 
	"strike" : "перечеркивание" , 
	"subscript" : "нижний индекс", 
	"superscript" : "верхний индекс", 
	"setfontcolor" : "Установите цвет шрифта" , 
	"fontcolorpicker" : "Выберите цвет шрифта", 
	"highlight" : "указание", 
	"highlightcolorpicker" : "выбери цвет указания", 
	"removeformat" : "устрани форматирование", 
	"addrule" : "прибавь линию", 
	"addlistnumeric" : "прибавь цифровой список", 
	"addlistbull" : "прибавь пунктирный список", 
	"leftjustify" : "форматирование к левой", 
	"centerjustify" : "центрирование", 
	"rightjustify" : "форматирование к правой", 
	"ident" : "отступ" , 
	"outdent" : "Удалить отступ", 
	"paragraph" : "новый параграф", 
	"attributes" : "Атрибуты", 
	"delete" : "удалять", 
	"elementoptions" : "варианты элемента", 
	"quit" : "Выход", 
	"sourcehtml" : "редактор HTML", 
	"visual" : "Визуальный редактор", 
	"inserthtmlform" : "вставь формуляр html", 
	"image" : "картинка", 
	"link" : "линк" , 
	"unlink" : "устрани линк", 
	"table" : "табель", 
	"insetfieldset" : "Прибавь элемент fieldset", 
	"insertinputtext" : "Вставь текстовое поле", 
	"insertinputpassword" : "Вставь поле на пароль", 
	"insertinputcheckbox" : "прибавь checkbox", 
	"insertinputradio" : "Прибавь input radio", 
	"insertinputsubmit" : "Прибавь submit", 
	"insertinputbutton" : "Прибавь кнопку", 
	"inserttextarea" : "Прибавь textarea", 
};